# Generated by Django 4.2 on 2023-04-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_posts"),
    ]

    operations = [
        migrations.RenameModel(old_name="Posts", new_name="Post",),
    ]
