# Generated by Django 4.2 on 2023-04-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_likepost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="no_of_likes", field=models.IntegerField(default=0),
        ),
    ]
